version: '3'

services:
  mongodb:
    restart: always
    image: mongo:4.2.3
    ports:
      - "27017:27017"
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - .docker/mongodb:/data/db

  api:
    build: .
    entrypoint: .docker/docker-entrypoint.sh
    container_name: delivery-nestjs-server
    environment:
      TZ: America/Sao_Paulo
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  # db:
  #   container_name: db_server
  #   build: .docker/postgres
  #   restart: always
  #   tty: true
  #   volumes:
  #     - .docker/dbdata:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_PASSWORD=root
  #     - POSTGRES_DB=sistema
